from typing import Protocol, runtime_checkable
@runtime_checkable
class Rollout(Protocol):
    def evaluate_action(self, act_seq, **kwargs): ...
    def compute_metrics_from_state(self, state, **kwargs): ...
    def compute_metrics_from_action(self, act_seq, **kwargs): ...
__all__ = ["Rollout"]
