from typing import Protocol, runtime_checkable
@runtime_checkable
class Rollout(Protocol):
    @property
    def action_dim(self): ...
    @property
    def action_horizon(self): ...
    @property
    def dt(self): ...
    @property
    def action_bound_lows(self): ...
    @property
    def action_bound_highs(self): ...
    def evaluate_action(self, act_seq, **kwargs): ...
    def compute_metrics_from_state(self, state, **kwargs): ...
    def compute_metrics_from_action(self, act_seq, **kwargs): ...
    def update_params(self, *args, **kwargs): ...
    def update_batch_size(self, batch_size): ...
    def update_dt(self, dt): ...
    def reset(self, *args, **kwargs): ...
    def reset_seed(self): ...
    def reset_shape(self): ...
__all__ = ["Rollout"]
