"""Structural optimizer protocol used by solver composition."""
from __future__ import annotations

from typing import Protocol, Optional, Any, Dict, List, Union, runtime_checkable
import torch

@runtime_checkable
class Optimizer(Protocol):
    @property
    def config(self) -> Any: ...
    @property
    def enabled(self) -> bool: ...
    @property
    def action_horizon(self) -> int: ...
    @property
    def action_dim(self) -> int: ...
    def optimize(self, seed_action: torch.Tensor) -> torch.Tensor: ...
    def reinitialize(self, action: torch.Tensor, mask: Optional[torch.Tensor]=None, clear_optimizer_state: bool=True, reset_num_iters: bool=False) -> None: ...
    def shift(self, shift_steps: int=0) -> None: ...
    def update_num_problems(self, num_problems: int) -> None: ...
    def update_rollout_params(self, goal: Any) -> None: ...
    def get_all_rollout_instances(self) -> list: ...
    def compute_metrics(self, action: torch.Tensor) -> Any: ...
    def reset_shape(self) -> None: ...
    def reset_seed(self) -> None: ...
    def reset_cuda_graph(self) -> None: ...
    def get_recorded_trace(self) -> Dict[str, Any]: ...
    def update_solver_params(self, solver_params: Dict[str, Dict[str, Any]]) -> bool: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
