"""Structural optimizer protocol used by solver composition."""
from typing import Protocol, Optional, Any, Dict, runtime_checkable
import torch

@runtime_checkable
class Optimizer(Protocol):
    config: Any
    @property
    def enabled(self) -> bool: ...
    @property
    def action_horizon(self) -> int: ...
    @property
    def action_dim(self) -> int: ...
    def optimize(self, seed_action: torch.Tensor) -> torch.Tensor: ...
    def reinitialize(self, action: torch.Tensor, mask: Optional[torch.Tensor]=None, clear_optimizer_state: bool=True, reset_num_iters: bool=False): ...
    def shift(self, shift_steps: int=0): ...
    def update_num_problems(self, num_problems: int): ...
    def update_rollout_params(self, goal: Any): ...
    def get_all_rollout_instances(self): ...
    def compute_metrics(self, action: torch.Tensor): ...
    def reset_shape(self): ...
    def reset_seed(self): ...
    def reset_cuda_graph(self): ...
    def get_recorded_trace(self): ...
    def update_solver_params(self, solver_params: Dict[str, Dict[str, Any]]): ...
    def enable(self): ...
    def disable(self): ...
